<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';require_admin();
$totalUsers=(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn();$totalPosts=(int)db()->query('SELECT COUNT(*) FROM gems')->fetchColumn();$activeReports=(int)db()->query("SELECT COUNT(*) FROM reports WHERE status='pending'")->fetchColumn();
$currentMonth=(int)db()->query("SELECT COUNT(*) FROM users WHERE created_at>=DATE_FORMAT(CURDATE(),'%Y-%m-01')")->fetchColumn();$previousMonth=(int)db()->query("SELECT COUNT(*) FROM users WHERE created_at>=DATE_FORMAT(CURDATE()-INTERVAL 1 MONTH,'%Y-%m-01') AND created_at<DATE_FORMAT(CURDATE(),'%Y-%m-01')")->fetchColumn();$growth=$previousMonth>0?(($currentMonth-$previousMonth)/$previousMonth*100):($currentMonth>0?100:0);
$recent=db()->query('SELECT a.*,u.full_name FROM activity_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 6')->fetchAll();$reports=db()->query("SELECT r.*,COALESCE(g.title,'Review report') AS content_title,u.full_name AS reporter FROM reports r LEFT JOIN gems g ON g.id=r.gem_id JOIN users u ON u.id=r.reporter_id WHERE r.status='pending' ORDER BY r.created_at DESC LIMIT 5")->fetchAll();
$pageTitle='Dashboard Overview';$activeAdmin='dashboard';require dirname(__DIR__).'/includes/admin-header.php';
?>
<div class="admin-page-head"><div><span class="eyebrow">Dashboard Overview</span><h1>Welcome back</h1><p class="muted">Manage your platform and community.</p></div><a class="btn btn-primary" href="<?=url('share.php')?>">+ Add Gem</a></div>
<div class="metric-grid"><div class="metric-card"><span>Total Users</span><strong><?=$totalUsers?></strong><small>Community accounts</small></div><div class="metric-card"><span>Total Posts</span><strong><?=$totalPosts?></strong><small>All gem submissions</small></div><div class="metric-card"><span>Active Reports</span><strong><?=$activeReports?></strong><small style="color:<?=$activeReports?'var(--red)':'var(--green)'?>">Need attention</small></div><div class="metric-card"><span>Monthly Growth</span><strong><?=number_format($growth,1)?>%</strong><small>Compared with last month</small></div></div>
<div class="admin-grid"><section class="admin-card"><div class="section-head"><h2>Recent Activity</h2><a class="btn btn-ghost btn-sm" href="<?=url('admin/analytics.php')?>">View analytics</a></div><div class="activity-list"><?php foreach($recent as $item):?><div class="activity-item"><span class="activity-dot"></span><div><p><?=e($item['description'])?></p><small><?=e(date('M j, Y H:i',strtotime($item['created_at'])))?></small></div></div><?php endforeach;?></div></section><section class="admin-card"><div class="section-head"><h2>Pending Reports</h2><a class="btn btn-ghost btn-sm" href="<?=url('admin/moderation.php?tab=reports')?>">Review all</a></div><?php if($reports):?><div class="activity-list"><?php foreach($reports as $report):?><div class="activity-item"><span class="activity-dot" style="background:var(--red)"></span><div><p><strong><?=e($report['content_title'])?></strong> · <?=e($report['violation_type'])?></p><small>Reported by <?=e($report['reporter'])?></small></div></div><?php endforeach;?></div><?php else:?><p class="muted">No active reports.</p><?php endif;?></section></div>
<section class="admin-card" style="margin-top:18px"><h2>Quick Actions</h2><div class="action-row"><a class="btn btn-soft" href="<?=url('admin/users.php')?>">Manage Users</a><a class="btn btn-soft" href="<?=url('admin/moderation.php')?>">Review Content</a><a class="btn btn-soft" href="<?=url('admin/analytics.php')?>">View Analytics</a><a class="btn btn-soft" href="<?=url('admin/settings.php')?>">Platform Settings</a></div></section>
<?php require dirname(__DIR__).'/includes/admin-footer.php'; ?>
