<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=(int)($_POST['user_id']??0);$role=(string)($_POST['role']??'user');$status=(string)($_POST['status']??'active');if($id===(int)current_user()['id']&&($role!=='admin'||$status!=='active'))flash('danger','You cannot demote or suspend your current administrator account.');elseif(in_array($role,['user','admin'],true)&&in_array($status,['active','suspended'],true)){$stmt=db()->prepare('UPDATE users SET role=?,status=? WHERE id=?');$stmt->execute([$role,$status,$id]);flash('success','User account updated.');}redirect('admin/users.php');}
$q=trim((string)($_GET['q']??''));$roleFilter=(string)($_GET['role']??'');$statusFilter=(string)($_GET['status']??'');$where=['1=1'];$params=[];if($q!==''){$where[]='(u.full_name LIKE ? OR u.email LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like);}if(in_array($roleFilter,['user','admin'],true)){$where[]='u.role=?';$params[]=$roleFilter;}if(in_array($statusFilter,['active','suspended'],true)){$where[]='u.status=?';$params[]=$statusFilter;}
$sql="SELECT u.*,(SELECT COUNT(*) FROM gems g WHERE g.user_id=u.id) AS posts,(SELECT COUNT(*) FROM saved_gems s WHERE s.user_id=u.id) AS saved FROM users u WHERE ".implode(' AND ',$where).' ORDER BY u.created_at DESC';$stmt=db()->prepare($sql);$stmt->execute($params);$users=$stmt->fetchAll();
$pageTitle='User Management';$activeAdmin='users';require dirname(__DIR__).'/includes/admin-header.php';
?>
<div class="admin-page-head"><div><span class="eyebrow">Community</span><h1>User Management</h1><p class="muted">Manage accounts, roles and access status.</p></div><span class="status-badge status-active"><?=count($users)?> users shown</span></div>
<form class="admin-filter-bar" method="get"><input class="form-control search-wide" name="q" value="<?=e($q)?>" placeholder="Search by name or email…"><select class="form-control" name="role"><option value="">All Roles</option><option value="admin" <?=$roleFilter==='admin'?'selected':''?>>Admin</option><option value="user" <?=$roleFilter==='user'?'selected':''?>>User</option></select><select class="form-control" name="status"><option value="">All Statuses</option><option value="active" <?=$statusFilter==='active'?'selected':''?>>Active</option><option value="suspended" <?=$statusFilter==='suspended'?'selected':''?>>Suspended</option></select><button class="btn btn-primary">Filter</button></form>
<div class="table-wrap"><table class="data-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Activity</th><th>Joined</th><th>Actions</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><strong><?=e($u['full_name'])?></strong><br><small><?=e($u['email'])?></small><br><small>Level <?=(int)$u['level']?> · <?=(int)$u['points']?> pts</small></td><td><?=e(ucfirst($u['role']))?></td><td><span class="status-badge status-<?=e($u['status'])?>"><?=e(ucfirst($u['status']))?></span></td><td><?=(int)$u['posts']?> posts · <?=(int)$u['saved']?> saved</td><td><?=e(date('Y-m-d',strtotime($u['created_at'])))?></td><td><form method="post" class="action-row"><?=csrf_field()?><input type="hidden" name="user_id" value="<?=(int)$u['id']?>"><select class="form-control" name="role" style="width:auto"><option value="user" <?=$u['role']==='user'?'selected':''?>>User</option><option value="admin" <?=$u['role']==='admin'?'selected':''?>>Admin</option></select><select class="form-control" name="status" style="width:auto"><option value="active" <?=$u['status']==='active'?'selected':''?>>Active</option><option value="suspended" <?=$u['status']==='suspended'?'selected':''?>>Suspended</option></select><button class="btn btn-primary btn-sm">Save</button></form></td></tr><?php endforeach;?></tbody></table></div>
<?php require dirname(__DIR__).'/includes/admin-footer.php'; ?>
