<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
$id=(int)($_GET['id']??0);
$stmt=db()->prepare("SELECT g.*,u.full_name AS contributor_name,(SELECT COUNT(*) FROM saved_gems WHERE gem_id=g.id) AS saves,(SELECT COUNT(*) FROM gem_likes WHERE gem_id=g.id) AS likes FROM gems g JOIN users u ON u.id=g.user_id WHERE g.id=? AND (g.status='approved' OR g.user_id=? OR ?=1) LIMIT 1");
$stmt->execute([$id,(int)(current_user()['id']??0),is_admin()?1:0]);$gem=$stmt->fetch();
if(!$gem){http_response_code(404);exit('Gem not found.');}
$images=gem_images($id);$stmt=db()->prepare("SELECT r.*,u.full_name,(SELECT COUNT(*) FROM review_likes rl WHERE rl.review_id=r.id) AS likes FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.gem_id=? AND (r.status='approved' OR r.user_id=?) ORDER BY r.status='approved' DESC,r.created_at DESC");$stmt->execute([$id,(int)(current_user()['id']??0)]);$reviews=$stmt->fetchAll();
$pageTitle=$gem['title'];require __DIR__.'/includes/header.php';
?>
<section class="detail-hero"><img src="<?=e(gem_image_url($gem,$images))?>" alt="<?=e($gem['title'])?>" onerror="this.onerror=null;this.src='<?=asset('images/gem-placeholder.svg')?>'"><div class="detail-overlay"></div><div class="detail-title"><span class="eyebrow" style="color:#fff"><?=e($gem['activity_type'])?></span><h1><?=e($gem['title'])?></h1><p>⌖ <?=e($gem['location'])?></p></div>
<div class="detail-actions"><?php if(is_logged_in()):?><form method="post" action="<?=url('toggle-like.php')?>"><?=csrf_field()?><input type="hidden" name="gem_id" value="<?=$id?>"><input type="hidden" name="return_to" value="gem.php?id=<?=$id?>"><button class="icon-btn<?=is_gem_liked($id)?' active':''?>" title="Like">♥</button></form><form method="post" action="<?=url('toggle-save.php')?>"><?=csrf_field()?><input type="hidden" name="gem_id" value="<?=$id?>"><input type="hidden" name="return_to" value="gem.php?id=<?=$id?>"><button class="icon-btn<?=is_gem_saved($id)?' active':''?>" title="Save">♡</button></form><?php endif;?></div></section>
<div class="container"><div class="stats-strip"><div class="stat-box"><strong><?=number_format((float)$gem['average_rating'],1)?></strong><span><?=e(render_stars((float)$gem['average_rating']))?></span></div><div class="stat-box"><strong><?=(int)$gem['review_count']?></strong><span>Reviews</span></div><div class="stat-box"><strong><?=e($gem['budget_level'])?></strong><span>Budget</span></div><div class="stat-box"><strong><?=e($gem['operating_hours'])?></strong><span>Hours</span></div></div>
<div class="detail-layout"><main>
<div class="content-card"><span class="eyebrow">Vibe & Activity</span><div class="tag-row"><?php foreach(tag_list($gem['vibes']) as $tag):?><span class="tag"><?=e($tag)?></span><?php endforeach;?><span class="tag"><?=e($gem['activity_type'])?></span></div><h2>About This Place</h2><p><?=nl2br(e($gem['description']))?></p></div>
<div class="content-card"><h2>Location</h2><div class="location-box"><div><div style="font-size:2rem">⌖</div><strong><?=e($gem['location'])?></strong><p class="muted"><?=e($gem['city'])?></p><a class="btn btn-ghost btn-sm" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=<?=urlencode($gem['location'])?>">Open in Maps</a></div></div></div>
<div class="content-card"><h2>Photo Gallery</h2><div class="gallery-grid"><img src="<?=e(gem_image_url($gem,$images))?>" alt="<?=e($gem['title'])?>" onerror="this.onerror=null;this.src='<?=asset('images/gem-placeholder.svg')?>'"><?php foreach($images as $image):?><img src="<?=e(str_starts_with($image['image_path'],'http')?$image['image_path']:url($image['image_path']))?>" alt="<?=e($image['alt_text']?:$gem['title'])?>" onerror="this.onerror=null;this.src='<?=asset('images/gem-placeholder.svg')?>'"><?php endforeach;?></div></div>
<div class="content-card" id="reviews"><div class="section-head"><div><h2>Community Reviews</h2><p class="muted">Authentic feedback from local explorers.</p></div><?php if(is_logged_in()):?><a class="btn btn-primary btn-sm" href="<?=url('review.php?gem_id='.$id)?>">Write a Review</a><?php endif;?></div>
<div class="review-list"><?php if($reviews):foreach($reviews as $review):?><article class="review-card"><div class="review-head"><div class="review-user"><span class="avatar"><?=e(mb_substr($review['full_name'],0,1))?></span><div><strong><?=e($review['full_name'])?></strong> <?php if($review['status']!=='approved'):?><span class="status-badge status-<?=e($review['status'])?>"><?=e(ucfirst($review['status']))?></span><?php endif;?><br><small><?=e(date('Y-m-d',strtotime($review['created_at'])))?><?=$review['is_edited']?' · edited':''?></small></div></div><span class="stars"><?=e(render_stars((float)$review['rating']))?></span></div><p><?=e($review['comment']?:'No written comment.')?></p><?php if(is_logged_in()&&$review['status']==='approved'):?><form method="post" action="<?=url('toggle-review-like.php')?>" class="inline-form"><?=csrf_field()?><input type="hidden" name="review_id" value="<?=(int)$review['id']?>"><input type="hidden" name="gem_id" value="<?=$id?>"><button class="btn btn-ghost btn-sm"><?=is_review_liked((int)$review['id'])?'♥':'♡'?> <?=(int)$review['likes']?> likes</button></form><?php else:?><small>♡ <?=(int)$review['likes']?> likes</small><?php endif;?><?php if(is_logged_in()&&(int)$review['user_id']!==(int)current_user()['id']):?><details style="margin-top:10px"><summary class="form-help" style="cursor:pointer">Report this review</summary><form method="post" action="<?=url('report.php')?>" class="action-row" style="margin-top:8px"><?=csrf_field()?><input type="hidden" name="gem_id" value="<?=$id?>"><input type="hidden" name="review_id" value="<?=(int)$review['id']?>"><select class="form-control" name="violation_type" required style="max-width:230px"><option value="">Select reason</option><option>Harassment or hate</option><option>Spam or advertising</option><option>False information</option><option>Inappropriate content</option></select><button class="btn btn-danger btn-sm">Report</button></form></details><?php endif;?></article><?php endforeach;else:?><div class="empty-state"><p>No approved reviews yet. Be the first to share your experience.</p></div><?php endif;?></div></div>
</main><aside><div class="sidebar-sticky"><div class="content-card"><h3>Plan your visit</h3><p class="muted">Shared by <?=e($gem['contributor_name'])?></p><a class="btn btn-primary btn-block" href="<?=is_logged_in()?url('review.php?gem_id='.$id):url('login.php')?>">Share Your Experience</a><?php if(is_logged_in()):?><form method="post" action="<?=url('report.php')?>" style="margin-top:10px"><?=csrf_field()?><input type="hidden" name="gem_id" value="<?=$id?>"><select class="form-control" name="violation_type" required><option value="">Report an issue…</option><option>Incorrect information</option><option>Inappropriate content</option><option>Duplicate listing</option><option>Closed permanently</option></select><textarea class="form-control" name="details" placeholder="Optional details" maxlength="400" style="margin-top:8px;min-height:80px"></textarea><button class="btn btn-ghost btn-block btn-sm" style="margin-top:8px">Submit Report</button></form><?php endif;?></div></div></aside></div></div>
<?php require __DIR__.'/includes/footer.php'; ?>
