<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';require_login();
$user=current_user();$userId=(int)$user['id'];$tab=(string)($_GET['tab']??'posted');if(!in_array($tab,['posted','saved','reviews'],true))$tab='posted';
$stmt=db()->prepare('SELECT COUNT(*) FROM gems WHERE user_id=?');$stmt->execute([$userId]);$postedCount=(int)$stmt->fetchColumn();
$stmt=db()->prepare('SELECT COUNT(*) FROM saved_gems WHERE user_id=?');$stmt->execute([$userId]);$savedCount=(int)$stmt->fetchColumn();
$stmt=db()->prepare('SELECT COUNT(*) FROM reviews WHERE user_id=?');$stmt->execute([$userId]);$reviewCount=(int)$stmt->fetchColumn();
$items=[];
if($tab==='posted'){$stmt=db()->prepare("SELECT g.*,(SELECT COUNT(*) FROM saved_gems WHERE gem_id=g.id) AS saves,(SELECT COUNT(*) FROM gem_likes WHERE gem_id=g.id) AS likes FROM gems g WHERE g.user_id=? ORDER BY g.created_at DESC");$stmt->execute([$userId]);$items=$stmt->fetchAll();}
elseif($tab==='saved'){$stmt=db()->prepare("SELECT g.*,(SELECT COUNT(*) FROM saved_gems WHERE gem_id=g.id) AS saves,(SELECT COUNT(*) FROM gem_likes WHERE gem_id=g.id) AS likes FROM saved_gems sg JOIN gems g ON g.id=sg.gem_id WHERE sg.user_id=? ORDER BY sg.created_at DESC");$stmt->execute([$userId]);$items=$stmt->fetchAll();}
else{$stmt=db()->prepare('SELECT r.*,g.title,g.id AS gem_id FROM reviews r JOIN gems g ON g.id=r.gem_id WHERE r.user_id=? ORDER BY r.created_at DESC');$stmt->execute([$userId]);$items=$stmt->fetchAll();}
$pageTitle='Your Profile';require __DIR__.'/includes/header.php';
?>
<section class="section-tight"><div class="container">
<div class="profile-banner"><div class="profile-avatar"><?=e(mb_strtoupper(mb_substr($user['full_name'],0,1)))?></div><div style="flex:1"><div class="action-row" style="align-items:center"><h1><?=e($user['full_name'])?></h1><?php if($user['role']==='admin'):?><span class="role-badge">ADMIN</span><?php endif;?></div><p class="profile-bio"><?=e($user['bio']?:$user['city'].' explorer sharing local favourites.')?></p><div class="profile-stats"><div class="profile-stat"><strong><?=$postedCount?></strong><span>Posted</span></div><div class="profile-stat"><strong><?=$savedCount?></strong><span>Saved</span></div><div class="profile-stat"><strong><?=$reviewCount?></strong><span>Reviews</span></div></div></div><div class="action-row"><a class="btn btn-ghost btn-sm" href="<?=url('settings.php')?>">⚙ Settings</a><?php if(is_admin()):?><a class="btn btn-secondary btn-sm" href="<?=url('admin/index.php')?>">Admin Panel</a><?php endif;?></div></div>
<nav class="tabs"><a class="<?=$tab==='posted'?'active':''?>" href="<?=url('profile.php?tab=posted')?>">Posted Gems</a><a class="<?=$tab==='saved'?'active':''?>" href="<?=url('profile.php?tab=saved')?>">Saved Gems</a><a class="<?=$tab==='reviews'?'active':''?>" href="<?=url('profile.php?tab=reviews')?>">My Reviews</a></nav>
<?php if($tab==='posted'):?>
<div class="dashboard-list"><?php if($items):foreach($items as $gem):?><div class="dashboard-item"><div><div class="action-row"><h3><?=e($gem['title'])?></h3><span class="status-badge status-<?=e($gem['status'])?>"><?=e(ucfirst($gem['status']))?></span></div><p class="muted"><?=e($gem['location'])?> · Submitted <?=e(date('Y-m-d',strtotime($gem['created_at'])))?></p><?php if($gem['rejection_reason']):?><p style="color:var(--red)">Reason: <?=e($gem['rejection_reason'])?></p><?php endif;?></div><div class="action-row"><a class="btn btn-ghost btn-sm" href="<?=url('gem.php?id='.(int)$gem['id'])?>">View</a><a class="btn btn-primary btn-sm" href="<?=url('edit-gem.php?id='.(int)$gem['id'])?>">Edit</a><form method="post" action="<?=url('delete-item.php')?>"><?=csrf_field()?><input type="hidden" name="type" value="gem"><input type="hidden" name="id" value="<?=(int)$gem['id']?>"><button class="btn btn-danger btn-sm" data-confirm="Delete this gem permanently?">Delete</button></form></div></div><?php endforeach;else:?><div class="empty-state"><p>You have not shared a gem yet.</p><a class="btn btn-primary" href="<?=url('share.php')?>">Share Your First Gem</a></div><?php endif;?></div>
<?php elseif($tab==='saved'):?>
<?php if($items):?><div class="gem-grid"><?php foreach($items as $gem){require __DIR__.'/includes/gem-card.php';}?></div><?php else:?><div class="empty-state"><p>No saved gems yet.</p><a class="btn btn-primary" href="<?=url('discover.php')?>">Explore Gems</a></div><?php endif;?>
<?php else:?>
<div class="dashboard-list"><?php if($items):foreach($items as $review):?><div class="dashboard-item"><div><div class="action-row"><h3><?=e($review['title'])?></h3><span class="status-badge status-<?=e($review['status'])?>"><?=e(ucfirst($review['status']))?></span></div><div class="stars"><?=e(render_stars((float)$review['rating']))?></div><p><?=e($review['comment']?:'No written comment.')?></p></div><div class="action-row"><a class="btn btn-ghost btn-sm" href="<?=url('gem.php?id='.(int)$review['gem_id'])?>">View Gem</a><a class="btn btn-primary btn-sm" href="<?=url('edit-review.php?id='.(int)$review['id'])?>">Edit</a><form method="post" action="<?=url('delete-item.php')?>"><?=csrf_field()?><input type="hidden" name="type" value="review"><input type="hidden" name="id" value="<?=(int)$review['id']?>"><button class="btn btn-danger btn-sm" data-confirm="Delete this review permanently?">Delete</button></form></div></div><?php endforeach;else:?><div class="empty-state"><p>You have not written any reviews yet.</p><a class="btn btn-primary" href="<?=url('discover.php')?>">Find a Gem to Review</a></div><?php endif;?></div>
<?php endif;?>
</div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
