<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';require_login();$userId=(int)current_user()['id'];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$gemId=(int)($_POST['gem_id']??0);$action=(string)($_POST['action']??'');if($action==='note'){$note=trim((string)($_POST['personal_note']??''));if(mb_strlen($note)>150)flash('danger','Personal note must be under 150 characters.');else{$stmt=db()->prepare('UPDATE saved_gems SET personal_note=? WHERE user_id=? AND gem_id=?');$stmt->execute([$note?:null,$userId,$gemId]);flash('success','Note saved successfully!');}}elseif($action==='remove'){$stmt=db()->prepare('DELETE FROM saved_gems WHERE user_id=? AND gem_id=?');$stmt->execute([$userId,$gemId]);flash('success','Gem removed from favourites.');}redirect('saved.php');}
$stmt=db()->prepare("SELECT g.*,sg.personal_note,sg.created_at AS saved_at,(SELECT COUNT(*) FROM saved_gems x WHERE x.gem_id=g.id) AS saves,(SELECT COUNT(*) FROM gem_likes l WHERE l.gem_id=g.id) AS likes FROM saved_gems sg JOIN gems g ON g.id=sg.gem_id WHERE sg.user_id=? ORDER BY sg.updated_at DESC");$stmt->execute([$userId]);$gems=$stmt->fetchAll();$pageTitle='Saved Gems';require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="container"><span class="eyebrow">Your favourites</span><h1>Saved Gems</h1><p class="muted"><?=count($gems)?> saved · Add private notes so you remember what matters.</p></div></section><section class="section-tight"><div class="container">
<?php if($gems):?><div class="saved-list"><?php foreach($gems as $gem):?><div class="saved-row"><?php require __DIR__.'/includes/gem-card.php';?><div class="note-card"><h3>Personal Note</h3><form method="post"><?=csrf_field()?><input type="hidden" name="gem_id" value="<?=(int)$gem['id']?>"><input type="hidden" name="action" value="note"><textarea class="form-control" name="personal_note" maxlength="150" data-char-counter="#note-count-<?=(int)$gem['id']?>" placeholder="Add your thoughts about this place…"><?=e($gem['personal_note'])?></textarea><div class="char-counter" id="note-count-<?=(int)$gem['id']?>">0/150</div><button class="btn btn-primary btn-sm" style="margin-top:10px">Save Note</button></form><form method="post" style="margin-top:8px"><?=csrf_field()?><input type="hidden" name="gem_id" value="<?=(int)$gem['id']?>"><input type="hidden" name="action" value="remove"><button class="btn btn-danger btn-sm" data-confirm="Are you sure you want to remove this gem from your favourites?">Remove from Favourites</button></form></div></div><?php endforeach;?></div><?php else:?><div class="empty-state"><div class="empty-icon">♡</div><h2>You haven't saved any gems yet</h2><p class="muted">Start exploring and save your favourites!</p><a class="btn btn-primary" href="<?=url('discover.php')?>">Explore Gems</a></div><?php endif;?></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
