<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';require_login();$user=current_user();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'profile');
 if($action==='profile'){$name=trim((string)($_POST['full_name']??''));$email=strtolower(trim((string)($_POST['email']??'')));$city=trim((string)($_POST['city']??''));$bio=trim((string)($_POST['bio']??''));if(mb_strlen($name)<2)$errors[]='Full name must contain at least 2 characters.';if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Enter a valid email address.';if(mb_strlen($bio)>300)$errors[]='Bio must be 300 characters or fewer.';$stmt=db()->prepare('SELECT id FROM users WHERE email=? AND id<>?');$stmt->execute([$email,(int)$user['id']]);if($stmt->fetch())$errors[]='That email address is already in use.';if(!$errors){$stmt=db()->prepare('UPDATE users SET full_name=?,email=?,city=?,bio=?,notify_new_gems=?,notify_comments=?,notify_likes_saves=?,personalized_recommendations=?,show_saved_gems=?,show_activity_status=? WHERE id=?');$stmt->execute([$name,$email,$city,$bio?:null,isset($_POST['notify_new_gems'])?1:0,isset($_POST['notify_comments'])?1:0,isset($_POST['notify_likes_saves'])?1:0,isset($_POST['personalized_recommendations'])?1:0,isset($_POST['show_saved_gems'])?1:0,isset($_POST['show_activity_status'])?1:0,(int)$user['id']]);flash('success','Profile settings saved.');redirect('settings.php');}}
 elseif($action==='password'){$current=(string)($_POST['current_password']??'');$password=(string)($_POST['new_password']??'');$confirm=(string)($_POST['confirm_password']??'');if(!password_verify($current,$user['password_hash']))$errors[]='Current password is incorrect.';if(strlen($password)<8)$errors[]='New password must contain at least 8 characters.';if($password!==$confirm)$errors[]='New passwords do not match.';if(!$errors){$stmt=db()->prepare('UPDATE users SET password_hash=? WHERE id=?');$stmt->execute([password_hash($password,PASSWORD_DEFAULT),(int)$user['id']]);$stmt=db()->prepare('DELETE FROM remember_tokens WHERE user_id=?');$stmt->execute([(int)$user['id']]);flash('success','Password changed successfully.');redirect('settings.php');}}
 elseif($action==='delete'){$confirm=trim((string)($_POST['confirm_text']??''));if($confirm!=='DELETE')$errors[]='Type DELETE to confirm permanent account deletion.';elseif(is_admin())$errors[]='The seeded administrator cannot delete the account from this screen. Create another administrator first.';else{$stmt=db()->prepare('DELETE FROM users WHERE id=?');$stmt->execute([(int)$user['id']]);logout_user();header('Location: '.url('index.php'));exit;}}
}
$pageTitle='Settings';require __DIR__.'/includes/header.php';$user=current_user();
?>
<section class="page-hero"><div class="container"><span class="eyebrow">Account</span><h1>Settings</h1><p class="muted">Configure your profile, notifications, privacy, and security.</p></div></section>
<section class="section-tight"><div class="container" style="max-width:980px"><?php if($errors):?><div class="toast toast-danger" style="position:static;margin-bottom:16px"><span><?=e(implode(' ',$errors))?></span></div><?php endif;?>
<form method="post"><?=csrf_field()?><input type="hidden" name="action" value="profile"><div class="settings-grid"><div class="settings-card"><h2>Profile Information</h2><div class="form-group"><label>Full Name</label><input class="form-control" name="full_name" value="<?=e($user['full_name'])?>" required></div><div class="form-group"><label>Email</label><input class="form-control" name="email" type="email" value="<?=e($user['email'])?>" required></div><div class="form-group"><label>City</label><input class="form-control" name="city" value="<?=e($user['city'])?>" required></div><div class="form-group"><label>Bio</label><textarea class="form-control" name="bio" maxlength="300"><?=e($user['bio'])?></textarea></div></div>
<div><div class="settings-card"><h2>Notifications</h2><?php foreach([['notify_new_gems','New Gems in Your City','Get notified about new places in your city on Mzansi Gem'],['notify_comments','Comments on Your Posts','When someone comments on your gems'],['notify_likes_saves','Likes & Saves','When someone likes or saves your gems']] as [$field,$title,$desc]):?><div class="toggle-row"><div><strong><?=e($title)?></strong><div class="form-help"><?=e($desc)?></div></div><label class="switch"><input type="checkbox" name="<?=e($field)?>" value="1" <?=$user[$field]?'checked':''?>><span></span></label></div><?php endforeach;?></div><div class="settings-card" style="margin-top:20px"><h2>Privacy</h2><?php foreach([['personalized_recommendations','Personalized Recommendations','Get suggestions based on your activity'],['show_saved_gems','Show Saved Gems on Profile','Let others see what you have saved'],['show_activity_status','Show Activity Status','Display when you are active']] as [$field,$title,$desc]):?><div class="toggle-row"><div><strong><?=e($title)?></strong><div class="form-help"><?=e($desc)?></div></div><label class="switch"><input type="checkbox" name="<?=e($field)?>" value="1" <?=$user[$field]?'checked':''?>><span></span></label></div><?php endforeach;?></div></div></div><button class="btn btn-primary btn-block" style="margin-top:20px">Save Changes</button></form>
<div class="settings-grid" style="margin-top:20px"><div class="settings-card"><h2>Change Password</h2><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="password"><div class="form-group"><label>Current Password</label><input class="form-control" type="password" name="current_password" required></div><div class="form-group"><label>New Password</label><input class="form-control" type="password" name="new_password" minlength="8" required></div><div class="form-group"><label>Confirm New Password</label><input class="form-control" type="password" name="confirm_password" required></div><button class="btn btn-secondary">Change Password</button></form></div><div class="settings-card danger-zone"><h2>Account Actions</h2><a class="btn btn-ghost btn-block" href="<?=url('logout.php')?>">Log Out</a><form method="post" style="margin-top:14px"><?=csrf_field()?><input type="hidden" name="action" value="delete"><div class="form-group"><label>Type DELETE to permanently delete your account</label><input class="form-control" name="confirm_text" placeholder="DELETE"></div><button class="btn btn-danger btn-block" data-confirm="This permanently deletes your account and all your content. Continue?">Delete Account</button></form></div></div>
</div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
