<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';require_login();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();remember_old_input($_POST);$title=trim((string)($_POST['title']??''));$description=trim((string)($_POST['description']??''));$location=trim((string)($_POST['location']??''));$city=trim((string)($_POST['city']??''));$vibes=$_POST['vibes']??[];$budget=(string)($_POST['budget_level']??'');$activity=(string)($_POST['activity_type']??'');$rating=(int)($_POST['rating']??0);$hours=trim((string)($_POST['operating_hours']??'All Day'));
 if(mb_strlen($title)<3||mb_strlen($title)>100)$errors[]='Name of place must be between 3 and 100 characters.';if(mb_strlen($description)<20||mb_strlen($description)>500)$errors[]='Description must be between 20 and 500 characters.';if($location==='')$errors[]='Location is required.';if($city==='')$errors[]='City is required.';if(!is_array($vibes)||count($vibes)<1||count($vibes)>3)$errors[]='Select between 1 and 3 vibes.';if(!in_array($budget,['Free','Budget','Mid-range','Premium'],true))$errors[]='Select a budget level.';if(!in_array($activity,['Food','Fitness','Study','Nature','Nightlife','Culture'],true))$errors[]='Select an activity type.';if($rating<1||$rating>5)$errors[]='Select a rating between 1 and 5 stars.';
 try{$uploads=validate_image_uploads($_FILES['images']??[],MAX_GEM_IMAGES);}catch(RuntimeException $e){$errors[]=$e->getMessage();$uploads=[];}
 $maxPosts=max(1,(int)setting('max_posts_per_day','10'));$stmt=db()->prepare('SELECT COUNT(*) FROM gems WHERE user_id=? AND created_at>=CURDATE()');$stmt->execute([(int)current_user()['id']]);if((int)$stmt->fetchColumn()>=$maxPosts)$errors[]='You have reached the daily submission limit.';
 if(!$errors){$baseSlug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$title),'-'));$slug=$baseSlug?:'gem';$n=2;$check=db()->prepare('SELECT id FROM gems WHERE slug=?');while(true){$check->execute([$slug]);if(!$check->fetch())break;$slug=$baseSlug.'-'.$n++;}
 $status=(setting('enable_moderation','1')==='1'&&setting('auto_approve_content','0')!=='1')?'pending':'approved';$paths=store_uploaded_images($uploads);$cover=$paths[0]??null;db()->beginTransaction();$stmt=db()->prepare('INSERT INTO gems(user_id,title,slug,description,location,city,vibes,budget_level,activity_type,operating_hours,cover_image,average_rating,review_count,status,approved_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([(int)current_user()['id'],$title,$slug,$description,$location,$city,implode(',',array_slice($vibes,0,3)),$budget,$activity,$hours?:'All Day',$cover,$status==='approved'?$rating:0,$status==='approved'?1:0,$status,$status==='approved'?date('Y-m-d H:i:s') : null]);$gemId=(int)db()->lastInsertId();foreach($paths as $i=>$path){$stmt=db()->prepare('INSERT INTO gem_images(gem_id,image_path,alt_text,sort_order) VALUES(?,?,?,?)');$stmt->execute([$gemId,$path,$title,$i]);}if($status==='approved'){$stmt=db()->prepare("INSERT INTO reviews(gem_id,user_id,rating,comment,status) VALUES(?,?,?,'Initial contributor rating','approved')");$stmt->execute([$gemId,(int)current_user()['id'],$rating]);}db()->commit();award_points((int)current_user()['id'],100);record_activity((int)current_user()['id'],'gem_submitted',current_user()['full_name'].' submitted '.$title.'.');clear_old_input();flash('success',$status==='pending'?'Your Mzansi Gem was submitted and is awaiting administrator approval.':'Your Mzansi Gem is now live!');redirect('profile.php');}
 }
$pageTitle='Share a Mzansi Gem';require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="container"><span class="eyebrow">Contribute</span><h1>Share a Mzansi Gem</h1><p class="muted">Add a lesser-known place that deserves more attention.</p></div></section><section class="section-tight"><div class="container" style="max-width:900px">
<?php if($errors):?><div class="toast toast-danger" style="position:static;margin-bottom:16px"><span><?=e(implode(' ',$errors))?></span></div><?php endif;?><div class="content-card"><form method="post" enctype="multipart/form-data"><?=csrf_field()?>
<div class="form-group"><label>Photos (up to 3)</label><div class="upload-drop"><input id="images" type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple data-image-preview="#image-preview"><p class="form-help">JPEG, PNG or WEBP, maximum 5 MB each.</p><div id="image-preview"></div></div></div>
<div class="form-group"><label>Name of Place *</label><input class="form-control" name="title" maxlength="100" value="<?=old('title')?>" required></div>
<div class="form-group"><label>Description *</label><textarea class="form-control" name="description" maxlength="500" data-char-counter="#description-count" placeholder="Tell us what makes this place special…" required><?=old('description')?></textarea><div class="char-counter" id="description-count">0/500</div></div>
<div class="form-row"><div class="form-group"><label>Location *</label><input class="form-control" name="location" value="<?=old('location')?>" placeholder="Woodstock, Cape Town" required></div><div class="form-group"><label>City *</label><select class="form-control" name="city" required><option value="">Select city</option><?php foreach(['Cape Town','Johannesburg','Durban','Pretoria','Gqeberha','Bloemfontein','Polokwane','Mbombela','East London','Kimberley'] as $c):?><option <?=old('city')===e($c)?'selected':''?>><?=e($c)?></option><?php endforeach;?></select></div></div>
<div class="form-group"><label>Operating Hours</label><input class="form-control" name="operating_hours" value="<?=old('operating_hours','All Day')?>" placeholder="e.g. 08:00 - 18:00"></div>
<div class="form-group"><label>Select Vibes (choose up to 3) *</label><div class="choice-row" data-max-checks="3"><?php foreach(['Chill','Romantic','Adventurous','Social','Quiet'] as $v):?><label class="choice-pill"><input type="checkbox" name="vibes[]" value="<?=e($v)?>" <?=in_array($v,$_POST['vibes']??[],true)?'checked':''?>><span><?=e($v)?></span></label><?php endforeach;?></div></div>
<div class="form-row"><div class="form-group"><label>Budget Level *</label><select class="form-control" name="budget_level"><option value="">Select budget</option><?php foreach(['Free','Budget','Mid-range','Premium'] as $o):?><option <?=old('budget_level')===e($o)?'selected':''?>><?=e($o)?></option><?php endforeach;?></select></div><div class="form-group"><label>Activity Type *</label><select class="form-control" name="activity_type"><option value="">Select activity</option><?php foreach(['Food','Fitness','Study','Nature','Nightlife','Culture'] as $o):?><option <?=old('activity_type')===e($o)?'selected':''?>><?=e($o)?></option><?php endforeach;?></select></div></div>
<div class="form-group"><label>Your Rating *</label><div class="star-input"><?php for($i=5;$i>=1;$i--):?><input id="share-star<?=$i?>" type="radio" name="rating" value="<?=$i?>" <?=((int)($_POST['rating']??0)===$i)?'checked':''?>><label for="share-star<?=$i?>">★</label><?php endfor;?></div></div>
<button class="btn btn-primary btn-block">✦ Share This Mzansi Gem</button></form></div></div></section>
<?php clear_old_input();require __DIR__.'/includes/footer.php'; ?>
